name: Build

on:
  workflow_call:

permissions: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read   # for actions/checkout, nothing else
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # actions/checkout v7.0.1
        with:
          persist-credentials: false

      - name: Report Go version
        run: go version

      - name: Build
        run: make build
